CREATE DATABASE course;

USE course;


CREATE TABLE AREA (
	DEPTNUM TINYINT,
	NOME CHAR(255),
	CIDADE CHAR(255)
);

SELECT * from AREA;


INSERT INTO AREA VALUES(10, 'CONTABILIDADE', 'OSASCO');
INSERT INTO AREA VALUES(20, 'PESQUISADOR', 'GUARULHOS');
INSERT INTO AREA VALUES(30, 'VENDAS', 'MAUA');
INSERT INTO AREA VALUES(40, 'OPERACOES', 'DIADEMA');

/*DROP table AREA; */

SELECT * FROM AREA WHERE DEPTNUM = 20;

