USE course;


CREATE TABLE FUN(
	FUNNUN INT,
	NOME VARCHAR(255),
	CARGO VARCHAR(255),
	MGR INT,
	CONTRATACAO DATE,
	SALARIO INT,
	COMISSAO INT,
	DEPTNUM INT
);


SELECT * FROM FUN;


INSERT INTO FUN VALUES(
	8369, 'SILVIA', 'ATENDENTE', 7902, '1980-12-17', 800, NULL, 20
);

INSERT INTO FUN VALUES(
	9499, 'ALAN', 'VENDEDOR', 7698, '1981-02-20', 1600, 300, 30
);

INSERT INTO FUN VALUES(
	6521, 'WALDIR', 'VENDEDOR', 7698, '1981-02-22', 1250, 500, 30
);

INSERT INTO FUN VALUES(
	9499, 'jOAO', 'VENDEDOR', 7698, '1981-04-02', 2975, NULL, 20
);


SELECT DEPTNUM, CARGO, SALARIO FROM FUN;

SELECT * FROM FUN WHERE DEPTNUM = 20;

SELECT NOME, CARGO FROM FUN WHERE DEPTNUM = 20;

SELECT * FROM FUN WHERE DEPTNUM = 10 OR
						COMISSAO IS NOT NULL OR
						SALARIO <= 2000 AND DEPTNUM = 20;

SELECT * FROM FUN WHERE (DEPTNUM = 10 OR  /*Bloco de código organizado por ( )*/
						COMISSAO IS NOT NULL OR
						SALARIO <= 2000) 
						AND DEPTNUM = 20;


SELECT SALARIO AS GANHOS, COMISSAO AS BONUS FROM FUN;


SELECT SALARIO AS GANHOS, COMISSAO AS BONUS FROM FUN WHERE COMISSAO < 5000;


SELECT * FROM (SELECT SALARIO AS GANHOS, COMISSAO AS BONUS FROM FUN) X WHERE GANHOS < 5000;


SELECT * FROM (SELECT SALARIO AS GANHOS, COMISSAO AS BONUS FROM FUN) X WHERE BONUS < 5000;


SELECT CONCAT(NOME,' CARGO as C ', CARGO) AS MSG FROM FUN WHERE DEPTNUM = 20;


SELECT NOME, SALARIO, CASE WHEN SALARIO <= 1000 THEN 'BAIXO' WHEN SALARIO >= 2000 THEN 'ALTO' ELSE 'MEDIO' END AS RESULTADO FROM FUN;


SELECT * FROM FUN LIMIT 2;


SELECT NOME, CARGO FROM FUN ORDER BY RAND() LIMIT 3;


SELECT NOME, CARGO FROM FUN ORDER BY NOME LIMIT 3;


SELECT NOME, COMISSAO FROM FUN WHERE COMISSAO IS NOT NULL;


SELECT NOME, COMISSAO FROM FUN WHERE COMISSAO IS NULL;


SELECT COALESCE(COMISSAO, 0) FROM FUN;


SELECT NOME, CARGO, COALESCE(COMISSAO, 0) FROM FUN WHERE COMISSAO IS NULL;


SELECT NOME, CARGO, COALESCE(COMISSAO, 'ZERO') FROM FUN WHERE COMISSAO IS NULL;


SELECT NOME, CARGO, COALESCE(COMISSAO, 'ZERO') FROM FUN WHERE COMISSAO IS NULL ORDER BY NOME DESC;


SELECT NOME, CARGO, SALARIO FROM FUN WHERE DEPTNUM = 20 ORDER BY SALARIO ASC;


SELECT NOME, CARGO, SALARIO FROM FUN WHERE DEPTNUM = 20 ORDER BY SALARIO DESC;


SELECT NOME, CARGO, SALARIO FROM FUN WHERE DEPTNUM = 20 ORDER BY 2 DESC;


SELECT FUNNUN, DEPTNUM, SALARIO, NOME, CARGO FROM FUN ORDER BY 5 DESC;


SELECT FUNNUN, DEPTNUM, SALARIO, NOME, CARGO FROM FUN ORDER BY 5 ASC;


SELECT NOME, SALARIO, COMISSAO FROM (SELECT NOME, SALARIO, COMISSAO, CASE WHEN COMISSAO IS NULL THEN 0 ELSE 1 END AS IS_NULL FROM FUN) X ORDER BY IS_NULL DESC, COMISSAO;


SELECT NOME, SALARIO, COMISSAO, CASE WHEN COMISSAO IS NULL THEN 0 ELSE 1 END AS IS_NULL FROM FUN;


SELECT NOME, SALARIO, COMISSAO FROM (SELECT NOME, SALARIO, COMISSAO, CASE WHEN COMISSAO IS NULL THEN 0 ELSE 1 END AS IS_NULL FROM FUN) X ORDER BY IS_NULL DESC, COMISSAO DESC;


SELECT NOME, SALARIO, COMISSAO FROM (SELECT NOME, SALARIO, COMISSAO, CASE WHEN COMISSAO IS NULL THEN 0 ELSE 1 END AS IS_NULL FROM FUN) X ORDER BY IS_NULL, COMISSAO DESC;


